### PR TITLE
feat!: add types for `std-env`

### PR DESCRIPTION
**Pull request by danielroe**
also:
* correct package.json repo and contributors
* upgrade `ci-info` (supports Node 10+) - see https://github.com/watson/ci-info/blob/master/CHANGELOG.md#v200

### CODE REVIEW

**Comment by danielroe** [comment]
@pi0

**Comment by pi0** [comment]
Thanks for the PR @danielroe.

BTW generally it is not good practice to push for merge by pinging and combining multiple changes in single PR ;)

**Comment by pi0** [comment]
published as [std-env@3.0.0-alpha](https://www.npmjs.com/package/std-env/v/3.0.0-alpha) :rocket:

**Comment by danielroe** [comment]
:flushed: Only pinged you on PR b/c I couldn't ask for review. Sorry!

**Pull request merged**
